# HOMEWORK 6


GROUP NUMBER:

GROUP MEMBERS that participated in the production of this file:

Comments:

In this Homework we use the time-series approach to testing cactor models

### 1. 

In order to proceed you need Microsoft Excel  file "https://www.dropbox.com/s/hez02fvhxymvaqi/Homework6.xls?dl=1". 

In this problem set you will evaluate and test asset pricing models using the time-series framework. You will use the Gibbons, Ross, Shanken (GRS) test discussed in class. The most difficult part of the problem set is the GRS test. Many articles that use this test have a short summary of the procedure.

The above file contains four spreadsheets:
1)	30 industry value-weight portfolio returns
2)	10 portfolios formed on short-to-intermediate term past returns (from t 2 to t 12), *note that these portfolios start in 01/1927 rather than 07/1926
3)	25 portfolios formed on size and BE/ME,
4)	And, a proxy for the market portfolio (RM-RF).

### Part I:  30 Value-Weight Industry portfolios

a)	Using the 30 value-weighted industry portfolios, calculate the sample mean and standard deviation of returns for each of these portfolios. Is there a discernible pattern in the average returns or Sharpe-ratios of the portfolios?

b)	Estimate time series regressions, Rpt - Rft = a + βiM (RMt - Rft) + eit, for each of the 30 industry portfolios. Perform the multivariate GRS test; please report both the GRS F-statistic and its p-value. Use the market portfolio proxy RM-RF.

c)	What is the null hypothesis of the GRS test (be precise), and how is this a test of the CAPM?  Explain intuitively the GRS test.  How do the time-series regressions implicitly estimate the beta risk premium?

d)	Comment on the sign and the magnitude of the intercepts.  Does the CAPM have difficulty pricing any portfolios in particular? Why?




### Answer here:

In [1]:
#==============importing data=============
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
url="https://www.dropbox.com/s/hez02fvhxymvaqi/Homework6.xls?dl=1"
VWreturns=pd.read_excel(url, sheetname='Industry portfolios (VW)', skiprows=2,  index_col=0, 
                    parse_dates=True, na_values=-99.99)
VWreturns=VWreturns/100
VWreturns.head()

,Food,Beer,Smoke,Games,Books,Hshld,Clths,Hlth,Chems,Txtls,...,Telcm,Servs,BusEq,Paper,Trans,Whlsl,Rtail,Meals,Fin,Other
192607,0.0056,-0.0519,0.0129,0.0293,0.1097,-0.0048,0.0808,0.0177,0.0814,0.0039,...,0.0083,0.0922,0.0206,0.0770,0.0193,-0.2379,0.0007,0.0187,0.0037,0.0520
192608,0.0259,0.2703,0.0650,0.0055,0.1001,-0.0358,-0.0251,0.0425,0.0550,0.0814,...,0.0217,0.0202,0.0439,-0.0238,0.0488,0.0539,-0.0075,-0.0013,0.0446,0.0676
192609,0.0116,0.0402,0.0126,0.0658,-0.0099,0.0073,-0.0051,0.0069,0.0533,0.0231,...,0.0241,0.0225,0.0019,-0.0554,0.0005,-0.0787,0.0025,-0.0056,-0.0123,-0.0386
192610,-0.0306,-0.0331,0.0106,-0.0476,0.0947,-0.0468,0.0012,-0.0057,-0.0476,0.0100,...,-0.0011,-0.0200,-0.0109,-0.0508,-0.0264,-0.1538,-0.0220,-0.0411,-0.0516,-0.0849
192611,0.0635,0.0729,0.0455,0.0166,-0.0580,-0.0054,0.0187,0.0542,0.0520,0.0311,...,0.0163,0.0377,0.0364,0.0384,0.0160,0.0467,0.0652,0.0433,0.0224,0.0400

In [3]:
Pastreturn=pd.read_excel(url, sheetname='Past return portfolios', skiprows=8,  index_col=0, 
                    parse_dates=True, na_values=-99.99)
Pastreturn=Pastreturn/100
Pastreturn.head()

,Loser,2,3,4,5,6,7,8,9,Winner
Date,,,,,,,,,,
192701,-0.0332,-0.0462,0.0266,-0.0032,-0.0041,0.0096,0.0077,0.0036,-0.0043,-0.0024
192702,0.0749,0.0601,0.0833,0.0751,0.0380,0.0416,0.0281,0.0328,0.0421,0.0696
192703,-0.0320,-0.0299,-0.0398,-0.0476,-0.0048,-0.0240,0.0210,0.0061,0.0089,0.0547
192704,0.0153,-0.0287,-0.0246,-0.0134,0.0259,-0.0013,0.0205,-0.0059,0.0164,0.0549
192705,0.0398,0.0439,0.0590,0.0315,0.0625,0.0592,0.0466,0.0659,0.0816,0.0624

In [4]:
BEME=pd.read_excel(url, sheetname='25 size and BEME portfolios', skiprows=2,  index_col=0, 
                    parse_dates=True, na_values=-99.99)
BEME=BEME/100
BEME.head()

,Low,2,3,4,High,Low.1,2.1,3.1,4.1,High.1,...,Low.3,2.3,3.3,4.3,High.3,Low.4,2.4,3.4,4.4,High.4
BE/ME,,,,,,,,,,,,,,,,,,,,,
192607,0.0378,-0.0041,-0.0194,0.0035,0.0205,0.0219,0.0242,0.0049,-0.0158,-0.0033,...,0.0159,0.0153,0.0119,0.0027,0.0247,0.0345,0.0609,0.0203,0.0311,0.0056
192608,-0.0221,-0.0873,0.0244,0.0061,0.0840,0.0217,-0.0118,0.0401,0.0046,0.0617,...,0.0133,0.0387,0.0201,0.0217,0.0534,0.0101,0.0419,0.0201,0.0548,0.0776
192609,-0.0621,-0.0030,-0.0620,-0.0164,0.0086,-0.0185,-0.0126,0.0108,-0.0304,-0.0094,...,0.0109,-0.0053,-0.0173,0.0146,0.0087,-0.0129,0.0365,0.0010,-0.0075,-0.0243
192610,-0.0862,-0.0375,-0.0567,0.0572,-0.0255,-0.0180,-0.0327,-0.0507,-0.0805,-0.0132,...,-0.0334,-0.0266,-0.0203,-0.0311,-0.0535,-0.0274,-0.0301,-0.0224,-0.0467,-0.0581
192611,0.0347,0.0665,0.0226,-0.0470,0.0054,0.0291,-0.0237,0.0301,0.0466,0.0273,...,0.0344,0.0239,0.0374,0.0493,0.0182,0.0429,0.0253,0.0152,0.0366,0.0256

In [5]:
MKTRF=pd.read_excel(url, sheetname='Market, Rf', skiprows=1,  index_col=0, 
                    parse_dates=True, na_values=-99.99)
MKTRF=MKTRF/100
MKTRF.head()

         RM-RF      RF
192607  0.0296  0.0022
192608  0.0264  0.0025
192609  0.0036  0.0023
192610 -0.0324  0.0032
192611  0.0253  0.0031

In [6]:
#====================for a)==================
#a) Using the 30 value-weighted industry portfolios, calculate the sample mean and standard deviation of returns 
#for each of these portfolios. Is there a discernible pattern in the average returns or Sharpe-ratios of the portfolios?

vw_mean = VWreturns.mean()
vw_std = VWreturns.std()
vw_mean

Food     0.009880
Beer     0.012173
Smoke    0.011700
Games    0.011249
Books    0.009425
Hshld    0.009334
Clths    0.009534
Hlth     0.011066
Chems    0.010629
Txtls    0.010270
Cnstr    0.009407
Steel    0.009021
FabPr    0.010415
ElcEq    0.011820
Autos    0.010966
Carry    0.011270
Mines    0.008885
Coal     0.010490
Oil      0.010283
Util     0.008837
Telcm    0.008692
Servs    0.012095
BusEq    0.011211
Paper    0.010362
Trans    0.009284
Whlsl    0.008394
Rtail    0.010396
Meals    0.010677
Fin      0.010225
Other    0.008018
dtype: float64

In [7]:
#b) Estimate time series regressions, Rpt - Rft = a + βiM (RMt - Rft) + eit, for each of the 30 industry portfolios. 
#Perform the multivariate GRS test; please report both the GRS F-statistic and its p-value. Use the market portfolio 
#proxy RM-RF.

In [8]:
#==========Estimate time series regressions, Rpt - Rft = a + βiM (RMt - Rft) + eit, for each of the 30 industry portfolios. 
#Perform the multivariate GRS test; 
#please report both the GRS F-statistic and its p-value. Use the market portfolio proxy RM-RF.


#creating portfolio excess return
VWreturns.iloc[:,:VWreturns.shape[1]] = VWreturns.iloc[:,:VWreturns.shape[1]].subtract(MKTRF['RF'],axis=0)
VWreturns.head()

,Food,Beer,Smoke,Games,Books,Hshld,Clths,Hlth,Chems,Txtls,...,Telcm,Servs,BusEq,Paper,Trans,Whlsl,Rtail,Meals,Fin,Other
192607,0.0034,-0.0541,0.0107,0.0271,0.1075,-0.0070,0.0786,0.0155,0.0792,0.0017,...,0.0061,0.0900,0.0184,0.0748,0.0171,-0.2401,-0.0015,0.0165,0.0015,0.0498
192608,0.0234,0.2678,0.0625,0.0030,0.0976,-0.0383,-0.0276,0.0400,0.0525,0.0789,...,0.0192,0.0177,0.0414,-0.0263,0.0463,0.0514,-0.0100,-0.0038,0.0421,0.0651
192609,0.0093,0.0379,0.0103,0.0635,-0.0122,0.0050,-0.0074,0.0046,0.0510,0.0208,...,0.0218,0.0202,-0.0004,-0.0577,-0.0018,-0.0810,0.0002,-0.0079,-0.0146,-0.0409
192610,-0.0338,-0.0363,0.0074,-0.0508,0.0915,-0.0500,-0.0020,-0.0089,-0.0508,0.0068,...,-0.0043,-0.0232,-0.0141,-0.0540,-0.0296,-0.1570,-0.0252,-0.0443,-0.0548,-0.0881
192611,0.0604,0.0698,0.0424,0.0135,-0.0611,-0.0085,0.0156,0.0511,0.0489,0.0280,...,0.0132,0.0346,0.0333,0.0353,0.0129,0.0436,0.0621,0.0402,0.0193,0.0369

In [9]:
import statsmodels.api as sm

/Users/wenxinyi/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [10]:
#create Epsilons
Epsilons = VWreturns[:].iloc[:,0:30]*0
Epsilons.head()

,Food,Beer,Smoke,Games,Books,Hshld,Clths,Hlth,Chems,Txtls,...,Telcm,Servs,BusEq,Paper,Trans,Whlsl,Rtail,Meals,Fin,Other
192607,0.0,-0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,0.0,0.0,0.0
192608,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,-0.0,0.0,0.0
192609,0.0,0.0,0.0,0.0,-0.0,0.0,-0.0,0.0,0.0,0.0,...,0.0,0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0
192610,-0.0,-0.0,0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
192611,0.0,0.0,0.0,0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
#create estimates
Estimates = pd.DataFrame(VWreturns.iloc[:,0:30].mean())
Estimates.columns=['alpha_ts']
Estimates.head()

       alpha_ts
Food   0.007060
Beer   0.009352
Smoke  0.008880
Games  0.008429
Books  0.006604

In [12]:
#do the regression analysis
x = sm.add_constant(MKTRF.iloc[:1069,0])
for portfolios in VWreturns.columns[0:30]:
    y= VWreturns.loc[:,portfolios]
    results = sm.OLS(y,x).fit()
    Estimates.set_value(portfolios,'alpha_ts',results.params[0])
    Epsilons[portfolios]=results.resid

In [13]:
Sigma=Epsilons.cov() 
# sample size #即有多少个日期
T=Epsilons.shape[0]
# number of test assets
N=Epsilons.shape[1]
# sharpe ratio of the factor
SRmkt = MKTRF.iloc[:1069, 0].mean()/MKTRF.iloc[:1069, 0].std()#这里factor就是market，求market 的SR

In [14]:
# GRS stats
Chi2 = T/(1+SRmkt**2)*(Estimates.alpha_ts.values @ np.linalg.inv(Sigma.values) @ Estimates.alpha_ts.values.T)
Chi2

59.183077208150252

In [15]:
#F stats
F = T*(T-N-1)*Chi2/(N*(T-2))
F

2051.5727740662951

In [16]:
import scipy.stats as stats
1 - stats.chi2.cdf(Chi2, N)

0.0011548729529661239

In [17]:
#F.stat <- T * (T - N - 1) * W.u / (N * (T - 2))

### Part II:  10 Past Return portfolios

e)	Repeat parts a), b), and d) for the 10 past return portfolios.



 ### Answer here:

In [18]:
#===================a================
pr_mean = Pastreturn.mean()
pr_std = Pastreturn.std()

In [19]:
#================b================
Pastreturn.iloc[:,:10] = Pastreturn.iloc[:,:10].subtract(MKTRF['RF'],axis=0)
Pastreturn.head()

,Loser,2,3,4,5,6,7,8,9,Winner
Date,,,,,,,,,,
192701,-0.0357,-0.0487,0.0241,-0.0057,-0.0066,0.0071,0.0052,0.0011,-0.0068,-0.0049
192702,0.0723,0.0575,0.0807,0.0725,0.0354,0.0390,0.0255,0.0302,0.0395,0.0670
192703,-0.0350,-0.0329,-0.0428,-0.0506,-0.0078,-0.0270,0.0180,0.0031,0.0059,0.0517
192704,0.0128,-0.0312,-0.0271,-0.0159,0.0234,-0.0038,0.0180,-0.0084,0.0139,0.0524
192705,0.0368,0.0409,0.0560,0.0285,0.0595,0.0562,0.0436,0.0629,0.0786,0.0594

In [20]:
#create Epsilons
Epsilons2 = Pastreturn[:].iloc[:,0:10]*0
Epsilons2.head()

        Loser    2    3    4    5    6    7    8    9  Winner
Date
192701   -0.0 -0.0  0.0 -0.0 -0.0  0.0  0.0  0.0 -0.0    -0.0
192702    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0
192703   -0.0 -0.0 -0.0 -0.0 -0.0 -0.0  0.0  0.0  0.0     0.0
192704    0.0 -0.0 -0.0 -0.0  0.0 -0.0  0.0 -0.0  0.0     0.0
192705    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0

In [21]:
#create estimates
Estimates2 = pd.DataFrame(Pastreturn.iloc[:,0:10].mean())
Estimates2.columns=['alpha_ts']
Estimates2.head()

       alpha_ts
Loser  0.000207
2      0.004093
3      0.004662
4      0.005948
5      0.005985

In [22]:
#do the regression analysis
x2 = sm.add_constant(MKTRF.iloc[6:-4,0])
for portfolios in Pastreturn.columns[0:10]:
    y2= Pastreturn.loc[:,portfolios]
    results = sm.OLS(y2,x2).fit()
    Estimates2.set_value(portfolios,'alpha_ts',results.params[0])
    Epsilons2[portfolios]=results.resid

In [23]:
Sigma2 = Epsilons2.cov() 
# sample size #即有多少个日期
T2 = Epsilons2.shape[0]
# number of test assets
N2 = Epsilons2.shape[1]
# sharpe ratio of the factor
SRmkt2 = MKTRF.iloc[6:-4, 0].mean()/MKTRF.iloc[6:-4, 0].std()#这里factor就是market，求market 的SR

In [24]:
# GRS stats
Chi2_2 = T2/(1+SRmkt2**2)*(Estimates2.alpha_ts.values @ np.linalg.inv(Sigma2.values) @ Estimates2.alpha_ts.values.T)
Chi2_2

66.633644816960938

In [25]:
#F stats
F2 = T2*(T2-N2-1)*Chi2_2/(N2*(T2-2))
F2

7023.0731188814152

In [26]:
#p value
1 - stats.chi2.cdf(Chi2_2, N2)

1.971516283560959e-10

### Part III:  25 Size and BE/ME portfolios

f)	Repeat parts a), b), and d) for the 25 size and BE/ME portfolios.



 ### Answer here:

In [27]:
#=========a=========
bm_mean = BEME.mean()
bm_std = BEME.std()

In [28]:
#=========b=========
#computing excess return
BEME.iloc[:,:BEME.shape[1]] = BEME.iloc[:,:BEME.shape[1]].subtract(MKTRF['RF'],axis=0)
BEME.head()

,Low,2,3,4,High,Low.1,2.1,3.1,4.1,High.1,...,Low.3,2.3,3.3,4.3,High.3,Low.4,2.4,3.4,4.4,High.4
BE/ME,,,,,,,,,,,,,,,,,,,,,
192607,0.0356,-0.0063,-0.0216,0.0013,0.0183,0.0197,0.0220,0.0027,-0.0180,-0.0055,...,0.0137,0.0131,0.0097,0.0005,0.0225,0.0323,0.0587,0.0181,0.0289,0.0034
192608,-0.0246,-0.0898,0.0219,0.0036,0.0815,0.0192,-0.0143,0.0376,0.0021,0.0592,...,0.0108,0.0362,0.0176,0.0192,0.0509,0.0076,0.0394,0.0176,0.0523,0.0751
192609,-0.0644,-0.0053,-0.0643,-0.0187,0.0063,-0.0208,-0.0149,0.0085,-0.0327,-0.0117,...,0.0086,-0.0076,-0.0196,0.0123,0.0064,-0.0152,0.0342,-0.0013,-0.0098,-0.0266
192610,-0.0894,-0.0407,-0.0599,0.0540,-0.0287,-0.0212,-0.0359,-0.0539,-0.0837,-0.0164,...,-0.0366,-0.0298,-0.0235,-0.0343,-0.0567,-0.0306,-0.0333,-0.0256,-0.0499,-0.0613
192611,0.0316,0.0634,0.0195,-0.0501,0.0023,0.0260,-0.0268,0.0270,0.0435,0.0242,...,0.0313,0.0208,0.0343,0.0462,0.0151,0.0398,0.0222,0.0121,0.0335,0.0225

In [29]:
#create Epsilons
Epsilons3 = BEME[:].iloc[:,0:25]*0
Epsilons3.head()

,Low,2,3,4,High,Low.1,2.1,3.1,4.1,High.1,...,Low.3,2.3,3.3,4.3,High.3,Low.4,2.4,3.4,4.4,High.4
BE/ME,,,,,,,,,,,,,,,,,,,,,
192607,0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
192608,-0.0,-0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
192609,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,0.0,-0.0,-0.0,...,0.0,-0.0,-0.0,0.0,0.0,-0.0,0.0,-0.0,-0.0,-0.0
192610,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
192611,0.0,0.0,0.0,-0.0,0.0,0.0,-0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
#create estimates
Estimates3 = pd.DataFrame(BEME.iloc[:,0:25].mean())
Estimates3.columns=['alpha_ts']
Estimates3.head()

      alpha_ts
Low   0.005715
2     0.006985
3     0.010100
4     0.011734
High  0.013611

In [31]:
#do the regression analysis
x3 = sm.add_constant(MKTRF.iloc[:,0])
for portfolios in BEME.columns[0:25]:
    y3= BEME.loc[:,portfolios]
    results3 = sm.OLS(y3,x3).fit()
    Estimates3.set_value(portfolios,'alpha_ts',results3.params[0])
    Epsilons3[portfolios]=results3.resid

In [32]:
Sigma3 = Epsilons3.cov() 
# sample size #即有多少个日期
T3 = Epsilons3.shape[0]
# number of test assets
N3 = Epsilons3.shape[1]
# sharpe ratio of the factor
SRmkt3 = MKTRF.iloc[:, 0].mean()/MKTRF.iloc[:, 0].std()#这里factor就是market，求market 的SR

In [33]:
# GRS stats
Chi2_3 = T3/(1+SRmkt3**2)*(Estimates3.alpha_ts.values @ np.linalg.inv(Sigma3.values) @ Estimates3.alpha_ts.values.T)
Chi2_3

80.655680061480226

In [34]:
#F stats
F3 = T3*(T3-N3-1)*Chi2_3/(N3*(T3-2))
F3

3384.1677425639136

In [35]:
#p value
1 - stats.chi2.cdf(Chi2_3, N3)

9.0031425981074165e-08


g)	Repeat b) for the 25 size and BE/ME portfolios, but this time use the “in-sample” tangency portfolio of the 25 portfolios estimated over the entire sample period and use this portfolio in place of RM-RF.

1. Does the GRS test reject or fail to reject when you use the in-sample tangency portfolio as the market proxy?
2. Is this result surprising?

In [36]:
#用tangency portfolio代替market portfolio
Estimates3['AvgReturns'] = bm_mean
invcov = np.linalg.inv(BEME.iloc[:,0:25].cov())
Estimates3['Wmve']=(invcov @ Estimates3['AvgReturns'].values)#MVP的weight
BEME['MVE'] = BEME.iloc[:,0:25] @ Estimates3['Wmve'].values
#bruto force => SR for "in-sample" tangency portfolio
insample_SR = BEME['MVE'].mean()/BEME['MVE'].std()#每个月MVP的Sharpe Ratio

In [37]:
insample_SR

0.29550801719720976

In [38]:
Chi2_33 = T3/(1+insample_SR**2)*(Estimates3.alpha_ts.values @ np.linalg.inv(Sigma3.values) @ Estimates3.alpha_ts.values.T)
Chi2_33

75.2567849247406

In [39]:
#F stats
F33 = T3*(T3-N3-1)*Chi2_33/(N3*(T3-2))
F33

3157.6397813178805

In [40]:
#p value
1 - stats.chi2.cdf(Chi2_33, N3)

6.1975589038532064e-07


h)	Repeat g) using the “out-of-sample” tangency portfolio of the portfolios estimated over one half of the sample and then applied to returns of the other half and vice versa and then use this portfolio in place of RM-RF.  Construct the out-of-sample tangency portfolio as follows:

    1. First, we split the sample into two halves:  (1) take all observations from odd months in even years and even months in odd years (i.e., if starting in 1980, this would look like:  01/1980, 03/1980, . . . , 11/1980, 02/1981, 04/1981, . . . 12/1981, 01/1982, 03/1982, . . .); and (2) the opposite (take all observations from even months in even years and odd months in odd years).
    
    2.	Then, compute the tangency portfolio weights for the 25 portfolios using only the moments estimated from the first sample and apply them to returns in the second sample.
    
    3.	Then, do the reverse---compute the tangency portfolio weights from the second sample and apply those to returns in the first sample.
    4.	The resulting return series is your new tangency portfolio returns which you will use to repeat the cross-sectional tests.

    5. Does the GRS test reject or fail to reject when you use the out-of-sample tangency portfolio as the market proxy?  Why?  Is this result surprising?

In [41]:
newdf=BEME.loc[::2, :]
newdf.head()

,Low,2,3,4,High,Low.1,2.1,3.1,4.1,High.1,...,2.3,3.3,4.3,High.3,Low.4,2.4,3.4,4.4,High.4,MVE
BE/ME,,,,,,,,,,,,,,,,,,,,,
192607,0.0356,-0.0063,-0.0216,0.0013,0.0183,0.0197,0.0220,0.0027,-0.0180,-0.0055,...,0.0131,0.0097,0.0005,0.0225,0.0323,0.0587,0.0181,0.0289,0.0034,-0.049599
192609,-0.0644,-0.0053,-0.0643,-0.0187,0.0063,-0.0208,-0.0149,0.0085,-0.0327,-0.0117,...,-0.0076,-0.0196,0.0123,0.0064,-0.0152,0.0342,-0.0013,-0.0098,-0.0266,0.291417
192611,0.0316,0.0634,0.0195,-0.0501,0.0023,0.0260,-0.0268,0.0270,0.0435,0.0242,...,0.0208,0.0343,0.0462,0.0151,0.0398,0.0222,0.0121,0.0335,0.0225,-0.079112
192701,0.0020,-0.0855,-0.0504,0.0298,0.0177,0.0231,-0.0449,-0.0031,-0.0092,0.1081,...,0.0122,-0.0076,-0.0002,0.0706,-0.0103,0.0008,-0.0069,0.0030,0.0396,0.228317
192703,0.0610,-0.0205,-0.0813,-0.0267,-0.0387,-0.0209,-0.0082,-0.0232,-0.0089,-0.0085,...,-0.0014,-0.0164,-0.0169,0.0359,0.0028,0.0168,-0.0042,0.0018,-0.0414,-0.593466

In [42]:
BEME.index

Int64Index([192607, 192608, 192609, 192610, 192611, 192612, 192701, 192702,
            192703, 192704,
            ...
            201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509,
            201510, 201511],
           dtype='int64', name='BE/ME', length=1073)

In [43]:
Estimates2 = pd.DataFrame(Pastreturn.iloc[:,0:10].mean())


i)	Repeat b) for the 25 size and BE/ME portfolios, but use the “in-sample” tangency portfolio of the 30 value-weight industry portfolios estimated over the entire sample period in place of RM-RF.  Comment on how well you price the 25 size and BE/ME portfolios.  Is this surprising?  Why or why not?

In [44]:
#用tangency portfolio代替market portfolio

Estimates['AvgReturns'] = vw_mean
invcov_30 = np.linalg.inv(VWreturns.iloc[:,0:30].cov())
Estimates['Wmve']=(invcov_30 @ Estimates['AvgReturns'].values)#MVP的weight
VWreturns['MVE'] = VWreturns.iloc[:,0:30] @ Estimates['Wmve'].values
#bruto force => SR for "in-sample" tangency portfolio
insample_SR2 = VWreturns['MVE'].mean()/VWreturns['MVE'].std()#每个月MVP的Sharpe Ratio
insample_SR2

0.23731441956585453

In [45]:
#computing Chi squared
Chi2_33_2 = T3/(1+insample_SR2**2)*(Estimates3.alpha_ts.values @ np.linalg.inv(Sigma3.values) @ Estimates3.alpha_ts.values.T)
Chi2_33_2

77.46585064587461

In [46]:
#F stats
F33_2 = T3*(T3-N3-1)*Chi2_33_2/(N3*(T3-2))
F33_2

3250.3282187467998

In [47]:
#p value
1 - stats.chi2.cdf(Chi2_33_2, N3)

2.832023017207419e-07

j)	Repeat b) for the 25 size and BE/ME portfolios, but use the “in-sample” tangency portfolio of the 10 past return portfolios estimated over the entire sample period in place of RM-RF.  Comment on how well you price the 25 size and BE/ME portfolios.  Is this surprising?  Why or why not?

In [48]:
#用tangency portfolio代替market portfolio

Estimates2['AvgReturns'] = pr_mean
invcov_10 = np.linalg.inv(Pastreturn.iloc[:,0:10].cov())
Estimates2['Wmve']=(invcov_10 @ Estimates2['AvgReturns'].values)#MVP的weight
Pastreturn['MVE'] = Pastreturn.iloc[:,0:10] @ Estimates2['Wmve'].values
#bruto force => SR for "in-sample" tangency portfolio
insample_SR3 = Pastreturn['MVE'].mean()/Pastreturn['MVE'].std()#每个月MVP的Sharpe Ratio
insample_SR3

0.2676847302487756

In [49]:
#computing Chi squared
Chi2_33_3 = T3/(1+insample_SR3**2)*(Estimates3.alpha_ts.values @ np.linalg.inv(Sigma3.values) @ Estimates3.alpha_ts.values.T)
Chi2_33_3

76.35719892681216

In [50]:
#F stats
F33_3 = T3*(T3-N3-1)*Chi2_33_3/(N3*(T3-2))
F33_3

3203.8111801138193

In [51]:
#p value
1 - stats.chi2.cdf(Chi2_33_3, N3)

4.2002479327951647e-07

k)	Report the correlation matrix of the returns on the tangency portfolios of the 30 value-weighted industries, 10 past return portfolios, and 25 size and BE/ME portfolios.  Comment on these correlations in light of the results you found in i) and j).

In [52]:
np.corrcoef(Estimates2['AvgReturns'].values,Estimates2['AvgReturns'].values)

array([[ 1.,  1.],
       [ 1.,  1.]])

In [53]:
BEME['MVE']

BE/ME
192607   -0.049599
192608    0.433247
192609    0.291417
192610    0.351615
192611   -0.079112
192612   -0.085804
192701    0.228317
192702    0.481665
192703   -0.593466
192704   -0.021496
192705    0.815284
192706   -0.421354
192707   -0.082354
192708    0.055972
192709    0.117757
192710    0.079248
192711    0.020184
192712    0.283435
192801    0.410190
192802   -0.018696
192803    0.750035
192804    0.679127
192805    0.831708
192806   -0.231663
192807   -0.073724
192808    0.402528
192809    0.674233
192810    0.837394
192811    0.931973
192812    0.208958
            ...
201306   -0.221324
201307    0.451541
201308   -0.177581
201309    0.267330
201310    0.403815
201311    0.067506
201312    0.124408
201401   -0.706747
201402    0.416742
201403    0.079298
201404    0.178443
201405    0.221657
201406   -0.135392
201407   -0.027966
201408    0.205916
201409   -0.242315
201410    0.501183
201411    0.048232
201412   -0.074077
201501   -0.205277
201502    0.365043
201503    0.085426
201504   -0.033598
201505   -0.111520
201506   -0.095993
201507   -0.151084
201508    0.248544
201509    0.179592
201510    0.327967
201511   -0.065274
Name: MVE, Length: 1073, dtype: float64

In [54]:
BEME.corr()

,Low,2,3,4,High,Low.1,2.1,3.1,4.1,High.1,...,2.3,3.3,4.3,High.3,Low.4,2.4,3.4,4.4,High.4,MVE
Low,1.000000,0.712551,0.782934,0.770743,0.788500,0.773842,0.743891,0.765045,0.769572,0.787655,...,0.695050,0.691321,0.738769,0.702351,0.640364,0.636876,0.648902,0.658678,0.683145,0.205587
2,0.712551,1.000000,0.856626,0.898367,0.867773,0.860970,0.880268,0.870267,0.857963,0.828149,...,0.781241,0.779194,0.756777,0.754026,0.685362,0.679006,0.681684,0.697965,0.633193,0.294210
3,0.782934,0.856626,1.000000,0.926266,0.919910,0.845863,0.897938,0.909362,0.913639,0.894519,...,0.835161,0.841957,0.834743,0.831688,0.722160,0.736637,0.740657,0.775204,0.757673,0.423543
4,0.770743,0.898367,0.926266,1.000000,0.951000,0.866234,0.914986,0.932723,0.936653,0.914239,...,0.835580,0.846164,0.852480,0.849265,0.714272,0.737261,0.752526,0.788138,0.743737,0.516202
High,0.788500,0.867773,0.919910,0.951000,1.000000,0.833482,0.894049,0.906441,0.924263,0.936962,...,0.815728,0.840407,0.855755,0.863666,0.683083,0.718565,0.745272,0.792193,0.768865,0.520232
Low.1,0.773842,0.860970,0.845863,0.866234,0.833482,1.000000,0.920572,0.894779,0.870945,0.822861,...,0.854343,0.819129,0.800489,0.765766,0.786597,0.763455,0.722406,0.721051,0.670155,0.334796
2.1,0.743891,0.880268,0.897938,0.914986,0.894049,0.920572,1.000000,0.945213,0.929504,0.886934,...,0.901968,0.887776,0.862211,0.844498,0.794948,0.800260,0.787419,0.799451,0.723813,0.468954
3.1,0.765045,0.870267,0.909362,0.932723,0.906441,0.894779,0.945213,1.000000,0.956284,0.915938,...,0.906449,0.911195,0.894557,0.884073,0.792612,0.817539,0.816747,0.841562,0.770957,0.525917
4.1,0.769572,0.857963,0.913639,0.936653,0.924263,0.870945,0.929504,0.956284,1.000000,0.934703,...,0.900667,0.909273,0.914862,0.900844,0.767589,0.807865,0.832381,0.861889,0.801239,0.537862
High.1,0.787655,0.828149,0.894519,0.914239,0.936962,0.822861,0.886934,0.915938,0.934703,1.000000,...,0.862351,0.888343,0.904690,0.907000,0.733784,0.782530,0.807636,0.849901,0.829411,0.515600
Low.2,0.767015,0.851677,0.867329,0.861834,0.822977,0.920258,0.919980,0.905594,0.878870,0.839467,...,0.895334,0.862698,0.831155,0.797319,0.850506,0.818690,0.779341,0.762463,0.699321,0.394651
2.2,0.740691,0.812479,0.859236,0.862263,0.839704,0.894351,0.925467,0.928063,0.910903,0.878141,...,0.949724,0.926606,0.896640,0.857445,0.860674,0.878072,0.847101,0.838982,0.774953,0.537499
3.2,0.729261,0.809036,0.875358,0.880178,0.866001,0.853578,0.919704,0.947046,0.941661,0.906246,...,0.944799,0.943886,0.922458,0.897333,0.834436,0.871203,0.873602,0.886452,0.813331,0.557948
4.2,0.733738,0.821309,0.870611,0.896162,0.891908,0.834719,0.909400,0.937520,0.948135,0.923918,...,0.918779,0.945466,0.945202,0.924083,0.800009,0.849259,0.875707,0.899349,0.828868,0.549028
High.2,0.764602,0.785157,0.878546,0.879954,0.909453,0.802478,0.872541,0.908590,0.919961,0.932631,...,0.874719,0.898803,0.921971,0.926472,0.759839,0.809199,0.838547,0.888758,0.859479,0.498981
Low.3,0.704134,0.754547,0.773005,0.766549,0.733907,0.885093,0.866121,0.845034,0.817120,0.780212,...,0.912007,0.858768,0.820267,0.769021,0.908457,0.872203,0.805572,0.762769,0.696727,0.472463
2.3,0.695050,0.781241,0.835161,0.835580,0.815728,0.854343,0.901968,0.906449,0.900667,0.862351,...,1.000000,0.947620,0.900783,0.866890,0.884177,0.912916,0.888713,0.869177,0.790215,0.496415
3.3,0.691321,0.779194,0.841957,0.846164,0.840407,0.819129,0.887776,0.911195,0.909273,0.888343,...,0.947620,1.000000,0.933204,0.905317,0.847422,0.893211,0.898614,0.900077,0.821904,0.525269
4.3,0.738769,0.756777,0.834743,0.852480,0.855755,0.800489,0.862211,0.894557,0.914862,0.904690,...,0.900783,0.933204,1.000000,0.929785,0.809865,0.867441,0.893602,0.915131,0.861153,0.535020
High.3,0.702351,0.754026,0.831688,0.849265,0.863666,0.765766,0.844498,0.884073,0.900844,0.907000,...,0.866890,0.905317,0.929785,1.000000,0.764056,0.823779,0.861080,0.902695,0.872800,0.449484
Low.4,0.640364,0.685362,0.722160,0.714272,0.683083,0.786597,0.794948,0.792612,0.767589,0.733784,...,0.884177,0.847422,0.809865,0.764056,1.000000,0.908241,0.839342,0.801450,0.722971,0.495083
2.4,0.636876,0.679006,0.736637,0.737261,0.718565,0.763455,0.800260,0.817539,0.807865,0.782530,...,0.912916,0.893211,0.867441,0.823779,0.908241,1.000000,0.915719,0.873362,0.784615,0.509426
3.4,0.648902,0.681684,0.740657,0.752526,0.745272,0.722406,0.787419,0.816747,0.832381,0.807636,...,0.888713,0.898614,0.893602,0.861080,0.839342,0.915719,1.000000,0.923796,0.814018,0.494501
4.4,0.658678,0.697965,0.775204,0.788138,0.792193,0.721051,0.799451,0.841562,0.861889,0.849901,...,0.869177,0.900077,0.915131,0.902695,0.801450,0.873362,0.923796,1.000000,0.861978,0.438357
High.4,0.683145,0.633193,0.757673,0.743737,0.768865,0.670155,0.723813,0.770957,0.801239,0.829411,...,0.790215,0.821904,0.861153,0.872800,0.722971,0.784615,0.814018,0.861978,1.000000,0.422852
MVE,0.205587,0.294210,0.423543,0.516202,0.520232,0.334796,0.468954,0.525917,0.537862,0.515600,...,0.496415,0.525269,0.535020,0.449484,0.495083,0.509426,0.494501,0.438357,0.422852,1.000000